[package]
name = "vm_calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.26.2", features = [ "default" ], optional = true }
egui = { version = "0.26.2", optional = true }

[features]
# default = ["gui"]
gui = ["dep:eframe", "dep:egui"]

